"""Add farm weather

Revision ID: 3cc5f59610af
Revises: f819c4fbe4c1
Create Date: 2026-09-23 18:59:18.751012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc5f59610af'
down_revision: Union[str, Sequence[str], None] = 'f819c4fbe4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('weather', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'weather')
    # ### end Alembic commands ###
