CROPS = {
    "carrot": {
        "name": "Carrot",
        "seed_price": 10.0,
        "base_price": 3.0,
        "growth_rate": 0.15,
        "base_harvest_amount": 5.5,
        "seasons": ["spring", "summer", "fall"],
    },
    "tomato": {
        "name": "Tomato",
        "seed_price": 10.0,
        "base_price": 7.5,
        "growth_rate": 0.20,
        "base_harvest_amount": 7.5,
        "seasons": ["summer"],
    },
    "potato": {
        "name": "Potato",
        "seed_price": 10.0,
        "base_price": 3.0,
        "growth_rate": 0.15,
        "base_harvest_amount": 4.0,
        "seasons": ["spring", "summer"],
    },
    "eggplant": {
        "name": "Eggplant",
        "seed_price": 10.0,
        "base_price": 6.5,
        "growth_rate": 0.20,
        "base_harvest_amount": 7.5,
        "seasons": ["summer"],
    },
    "sweetcorn": {
        "name": "Sweetcorn",
        "seed_price": 10.0,
        "base_price": 4.5,
        "growth_rate": 0.20,
        "base_harvest_amount": 2.0,
        "seasons": ["summer"],
    },
    "pumpkin": {
        "name": "Pumpkin",
        "seed_price": 10.0,
        "base_price": 3.0,
        "growth_rate": 0.20,
        "base_harvest_amount": 3.5,
        "seasons": ["fall"],
    },
    "onion": {
        "name": "Onion",
        "seed_price": 10.0,
        "base_price": 3.0,
        "growth_rate": 0.15,
        "base_harvest_amount": 4.5,
        "seasons": ["spring", "fall"],
    },
    "watermelon": {
        "name": "Watermelon",
        "seed_price": 10.0,
        "base_price": 2.5,
        "growth_rate": 0.20,
        "base_harvest_amount": 3.5,
        "seasons": ["summer"],
    },
}

ITEMS = {"fertilizer": {"name": "Fertilizer", "price": 500.0}}
